packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/engines"
  - "@scarf/scarf"
  - msw
  - prisma
  - sharp
  - unrs-resolver
overrides:
  "@hono/node-server@<1.19.13": ">=1.19.13"
  postcss@<8.5.10: ">=8.5.10"
